- name: purge old-lxc if exists
  apt:
    name: lxc-docker
    state: absent

- name: Install Docker dependencies (APT)
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apparmor
    - apt-transport-https
    - ca-certificates
    - linux-image-extra-{{ ansible_kernel }}
    - linux-image-extra-virtual

- name: Add Docker APT repository key
  apt_key:
    id: "58118E89F3A912897C070ADBF76221572C52609D"
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"

- name: Add Docker APT repository
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Install Docker
  apt:
    name: docker-engine
    state: present

- name: Enable docker service
  service:
    enabled: yes
    name: docker
    state: started
