- name: set locales
  locale_gen: name=ja_JP.UTF-8 state=present
  when: ansible_distribution == 'Ubuntu'

- name: set hostname
  hostname: name="{{ inventory_hostname }}"

- name: set /etc/hosts
  lineinfile:
    dest: "/etc/hosts"
    state: present
    create: yes
    line: "127.0.0.1 {{ inventory_hostname }}"

- name: create common group
  group:
    name: "{{ user_name }}"

- name: create common user
  user:
    name: "{{ user_name }}"
    groups: "{{ user_name }},systemd-journal"
    shell: /bin/bash
    state: present

- name: set sudoers
  template:
    src: sudoers.j2
    dest: "/etc/sudoers.d/{{ user_name }}"
    owner: root
    group: root 
    mode: 0440

- name: add authorized_keys from github
  authorized_key:
    user: "{{ user_name }}"
    key: "https://github.com/{{ item }}.keys "
  with_items: "{{ developer_pub_keys }}"

