- name: sysctl
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - {"key": "net.core.somaxconn", "value": 65535}
    - {"key": "net.ipv4.tcp_max_syn_backlog", "value": 65535}
    - {"key": "net.core.netdev_max_backlog", "value": 16384}
    - {"key": "fs.file-max", "value": 1232457}
    - {"key": "kernel.threads-max", "value": 1232457}

- name: ulimit
  pam_limits:
    domain: "*"
    limit_type: "{{ item.type }}"
    limit_item: "{{ item.item }}"
    value: "{{ item.value }}"
  with_items:
    - {"type": "soft", "item": "nofile" ,"value": 65536}
    - {"type": "hard", "item": "nofile" ,"value": 65536}
    
      
